config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/vermaseren/form:
      branch: master
      repo: https://github.com/vermaseren/form
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/vermaseren/form git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-champagne-llama.sh
        container: qc.acc_stealthy-aquamarine-shrimp
  QC.Doc:
    repos:
      github.com/vermaseren/form find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-harlequin-loon.sh
        container: qc.doc_sloppy-wisteria-hamster
      github.com/vermaseren/form git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-champagne-jackal.sh
        container: qc.doc_pasty-taupe-ragdoll
      github.com/vermaseren/form markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-emerald-toucan.sh
        container: qc.doc_bluesy-saffron-monster
  QC.Lic:
    repos:
      github.com/vermaseren/form licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-celadon-cheetah.sh
        container: qc.lic_crappy-apricot-chinook
  QC.Sty:
    repos:
      github.com/vermaseren/form rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-salmon-chamois.sh
        container: qc.sty_beady-taupe-fish
  QC.Ver:
    repos:
      github.com/vermaseren/form get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-charcoal-llama.sh
        container: qc.ver_snappy-amber-llama
timeout: 1800
