config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/vermaseren/form:
      branch: master
      repo: https://github.com/vermaseren/form
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/vermaseren/form git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-azure-frigatebird.sh
        container: qc.acc_gloppy-beige-frise
  QC.Doc:
    repos:
      github.com/vermaseren/form find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-auburn-woodlouse.sh
        container: qc.doc_gummy-cerise-tang
      github.com/vermaseren/form git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-turquoise-hound.sh
        container: qc.doc_pokey-vermilion-tetra
      github.com/vermaseren/form markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-corn-coral.sh
        container: qc.doc_whiny-malachite-guppy
  QC.Lic:
    repos:
      github.com/vermaseren/form licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-saffron-russel.sh
        container: qc.lic_pasty-buff-squirt
  QC.Sty:
    repos:
      github.com/vermaseren/form rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chocolate-tetra.sh
        container: qc.sty_lanky-vermilion-oriole
  QC.Ver:
    repos:
      github.com/vermaseren/form get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ultramarine-crane.sh
        container: qc.ver_homey-brown-eel
timeout: 1800
